---
driver:
  name: exec

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 17.10.114
  install_strategy: always
  chef_license: accept-no-persist

verifier:
  name: inspec

platforms:
  - name: windows-2025
  - name: windows-2022

suites:
  - name: windows
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[data-bag-faker]
      - recipe[sumologic-collector::windows]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>

  - name: default-resource
    run_list:
      - recipe[default-resource]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>

  - name: default-resource-install
    run_list:
      - recipe[default-resource::install]

  - name: default-resource-configure
    run_list:
      - recipe[default-resource::configure]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>

  - name: default-resource-remove
    run_list:
      - recipe[default-resource::remove]

  - name: installer-resource
    run_list:
      - recipe[installer-resource]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>

  - name: source-resource
    run_list:
      - recipe[source-resource]
      - recipe[source-resource::local_file_create]
      - recipe[source-resource::local_win_event_log_create]
      - recipe[source-resource::remote_file_create]
      - recipe[source-resource::remote_win_event_log_create]
      - recipe[source-resource::script_create]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>
