# frozen_string_literal: true

# InSpec test for default-resource-configure suite

sumo_dir = os.windows? ? 'c:\sumo' : '/opt/SumoCollector'

describe file("#{sumo_dir}/config") do
  it { should exist }
  it { should be_directory }
end

describe file("#{sumo_dir}/config/user.properties") do
  it { should exist }
  its('content') { should match(/Generated by Chef/) }
  its('content') { should match(/name=test-instance/) }
  its('content') { should match(/hostName=example\.com/) }
  its('content') { should match(/description=A Test Kitchen instance/) }
  its('content') { should match(/category=Misc/) }
  its('content') { should match(/ephemeral=true/) }
  its('content') { should match(/proxyHost=proxy.test.com/) }
  its('content') { should match(/proxyPort=8080/) }
  its('content') { should match(/installerMode=true/) }
  its('content') { should match(%r{timeZone=Etc/UTC}) }
end
