name: Integration Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  # Linux integration tests using Docker driver
  linux-integration:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-22.04
          - ubuntu-20.04
          - debian-10
          - debian-11
          - debian-12
    name: "Linux (${{ matrix.platform }})"
    uses: ./.github/workflows/_workflow_IT-runner.yaml
    with:
      runs-on: ubuntu-latest
      driver: docker
      kitchen-config: .kitchen.docker.yml
      platform: ${{ matrix.platform }}
    secrets:
      SUMO_ACCESS_ID: ${{ secrets.SUMO_ACCESS_ID }}
      SUMO_ACCESS_KEY: ${{ secrets.SUMO_ACCESS_KEY }}

  # Windows integration tests
  windows-integration:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-2022
            runs-on: windows-2022
          - platform: windows-2019
            runs-on: windows-2019
    name: "Windows (${{ matrix.platform }})"
    uses: ./.github/workflows/_workflow_IT-runner.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
      driver: exec
      kitchen-config: .kitchen.windows.yml
      platform: ${{ matrix.platform }}
    secrets:
      SUMO_ACCESS_ID: ${{ secrets.SUMO_ACCESS_ID }}
      SUMO_ACCESS_KEY: ${{ secrets.SUMO_ACCESS_KEY }}
